# .pre-commit-config.yaml
# Install:  pip install pre-commit && pre-commit install
# Update:   pre-commit autoupdate

default_language_version:
  python: python3.12

exclude: |
  (?x)^(
    build/|
    dist/|
    \.venv/|
    venv/|
    env/|
    .*\.egg-info/
  )

repos:
  # Basic hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: debug-statements
      - id: check-added-large-files
        args: [--maxkb=500]

  # Ruff: lint (incl. import sorting via I rules) + format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args:
          - --fix
          - "--select=E,F,I"
      - id: ruff-format

  # Static typing
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-setuptools
        args:
          - --ignore-missing-imports
          - --warn-redundant-casts
          - --warn-unused-ignores
          - --no-warn-no-return
          - --pretty
        files: ^(src/|.*\.py)$

  # Security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-q]
        exclude: ^tests/
