# .pre-commit-config.yaml
# Install:  pip install pre-commit
# Enable:   pre-commit install
# Update:   pre-commit autoupdate

default_language_version:
  python: python3.12

exclude: |
  (?x)^(
    build/|
    dist/|
    \.venv/|
    venv/|
    env/|
    .*\.egg-info/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: debug-statements
      - id: check-added-large-files
        args: [--maxkb=500]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: [--line-length=100]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-setuptools
        args:
          - --ignore-missing-imports
          - --warn-redundant-casts
          - --warn-unused-ignores
          - --no-warn-no-return
          - --pretty
        files: ^(src/|.*\.py)$

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-q]
        exclude: ^tests/
